---

#Geerlingguy variables, do not change these unless you are very familiar with these playbooks

### geerlingguy.mysql

#Without this we get "ERROR 1709 (HY000) at line 358: Index column size too large. The maximum column size is 767 bytes."
#This key makes innodb_large_prefix=1 and innodb_file_format=barracuda in /etc/mysql/my.cnf
mysql_supports_innodb_large_prefix: False

# TODO: Handle setting appropriate host restictions
mysql_users:
  - name: "{{ oc_db_user }}"
    host: "%"
    password: "{{ oc_db_pass }}"
    priv: "{{ oc_db_schema }}.*:ALL"

#Only set the root password if we're the first ones configuring, otherwise ignore the setting below
mysql_root_password_update: false

#The root mysql/mariadb password
mysql_root_password: "{{ ansible_date_time.epoch | to_uuid }}"

