---

es_version: 7.10.2
es_api_host: "{{ inventory_hostname }}"
es_use_repository: true
es_add_repository: false
oss_version: true

es_config:
  node.name: "{{ inventory_hostname }}"
  network.host: "{{ inventory_hostname }}"
  discovery.seed_hosts: ["{{ inventory_hostname }}"]
  cluster.initial_master_nodes: ["{{ inventory_hostname }}"]

