---

nginx_manage_repo: false
nginx_install_from: os_repository
nginx_setup_license: false
nginx_selinux: true
nginx_config_selinux: true
nginx_config_selinux_tcp_ports:
  - 80
nginx_config_http_template_enable: true
nginx_config_http_template:
  - deployment_location: /etc/nginx/conf.d/{{ inventory_hostname }}.conf
    config:
      servers:
        - core:
            listen:
              - address: 0.0.0.0
                port: 80
            client_max_body_size: 0
            server_name: "{{ inventory_hostname }}"
          locations:
            - location: /
              proxy:
                pass: http://127.0.0.1:8080
                buffering: false
                request_buffering: false
                set_header:
                  - field: Host
                    value: $host
                  - field: X-Real-IP
                    value: $remote_addr
                  - field: X-Forwarded-For
                    value: $proxy_add_x_forwarded_for
                  - field: X-Forwarded-Proto
                    value: $scheme
