---
    nginx_config_cleanup: false
    nginx_config_selinux: true
    nginx_config_selinux_tcp_ports:
      - 80
      - 443

    nginx_config_http_template_enable: true
    nginx_config_http_template:
      - template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        servers:
          - listen:
              - ip: 0.0.0.0
                port: 80
                opts:
                  - default_server
            client_max_body_size: 0m
            server_name: "{{ inventory_hostname }}"
            error_page: /usr/share/nginx/html
            autoindex: false
            locations:
              - location: /
                proxy_pass: http://localhost:8080
                proxy:
                  - buffering: false
                    set_header:
                      - field: X-Real-IP
                        value: $remote_addr
                      - field: X-Forwarded-For
                        value: $proxy_add_x_forwarded_for
                      - field: X-Forwarded-Proto
                        value: $scheme
