---

- name: Loading platform variables
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: Installing runtime dependencies
  package:
    name: "{{ lookup('vars', opencast_node_type) }}"
    state: latest
    update_cache: yes
  become: yes
  register: packages
  until: packages is not failed
  retries: 5
  delay: 3
