---
# This playbook configures a full Opencast cluster.
# Run opencast.yml first to install everything, then use this to reconfigure things.

- hosts: database
  user: "{{ ansible_user }}"

  roles:
    - { role: mariadb-config }
  handlers:
    - include: handlers/restarts.yml


- hosts: nginx
  user: "{{ ansible_user }}"
  roles:
    - { role: nginxinc.nginx_config, when: install_nginx | bool, become: yes }


- hosts: opencast
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-config }
  handlers:
    - include: handlers/restarts.yml

