---
# This playbook deploys a full Opencast cluster from packages

- hosts: fileserver
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-create-user }
    - { role: geerlingguy.nfs, when: handle_network_mounts | bool, become: yes }
  vars_files:
    - group_vars/geerlingguy.yml


- hosts: database
  user: "{{ ansible_user }}"

  roles:
    - { role: geerlingguy.mysql, when: install_mariadb | bool, become: yes }
    - { role: mariadb-config }
  handlers:
    - include: handlers/restarts.yml
  vars_files:
    - group_vars/geerlingguy.yml


- hosts: activemq
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-create-user }
    - { role: opencast-packages-repo-setup }
    - { role: opencast-shims }
    - { role: activemq-packages-install }
    - { role: activemq-config }
  handlers:
    - include: handlers/restarts.yml


- hosts: opencast
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-create-user }
    - { role: opencast-shims }
    - { role: nfs-client, when: handle_network_mounts | bool }
    - { role: opencast-packages-repo-setup }
    - { role: packaged-opencast-runtime-deps }
    - { role: geerlingguy.nginx, become: yes }
    - { role: opencast-packages-install }
    - { role: opencast-config }
  handlers:
    - include: handlers/restarts.yml
  vars_files:
    - group_vars/geerlingguy.yml

