---
# This playbook deploys a full Opencast cluster from packages

- hosts: all
  user: "{{ ansible_user }}"
  tasks:
    - name: Gather facts from cluster
      setup:
      delegate_to: "{{item}}"
      delegate_facts: True
      loop: "{{groups['opencast']}}"

    - name: Check if uninstall tag is present
      command: /bin/true
      register: uninstall
      tags:
        - never
        - uninstall

    - name: Check if reset tag is present
      command: /bin/true
      register: reset
      tags:
        - never
        - reset

- hosts: fileserver
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-create-user, tags: [ "opencast" ] }
    - { role: geerlingguy.nfs, when: handle_network_mounts | bool, become: yes }
  vars_files:
    - group_vars/geerlingguy.yml


- hosts: database
  user: "{{ ansible_user }}"

  roles:
    - { role: geerlingguy.mysql, when: install_mariadb | bool, become: yes }
    - { role: mariadb-config, tags: [ "opencast" ] }
  handlers:
    - include: handlers/restarts.yml
  vars_files:
    - group_vars/geerlingguy.yml


- hosts: activemq
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-create-user, tags: [ "opencast" ] }
    - { role: opencast-packages-repo-setup, tags: [ "opencast" ] }
    - { role: opencast-shims, tags: [ "opencast" ] }
    - { role: activemq-packages-install }
    - { role: activemq-config, tags: [ 'config' ] }
  handlers:
    - include: handlers/restarts.yml


- hosts: opencast
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-create-user, tags: [ "opencast" ] }
    - { role: opencast-shims, tags: [ "opencast" ] }
    - { role: nfs-client, when: handle_network_mounts | bool }
    - { role: opencast-packages-repo-setup, tags: [ "opencast" ] }
    - { role: packaged-opencast-runtime-deps }
    - { role: geerlingguy.nginx, become: yes }
    - { role: opencast-packages-install, tags: [ "opencast" ] }
    - { role: opencast-clean, tags: [ "never", "reset" ] }
    - { role: opencast-config, tags: [ "opencast", "config" ] }
    - { role: opencast-packages-uninstall, tags: [ "never", "uninstall" ] }
  handlers:
    - include: handlers/restarts.yml
  vars_files:
    - group_vars/geerlingguy.yml

