---
# This playbook deploys a full Opencast cluster from packages

- hosts: all
  user: "{{ ansible_user }}"
  tasks:
    - name: Autocorrect major version for Amazon, NA -> 7
      set_fact: ansible_distribution_major_version="7"
      when: ansible_distribution == 'Amazon'

- hosts: fileserver
  user: "{{ ansible_user }}"

  roles:
    - { role: geerlingguy.nfs, when: handle_network_mounts | bool, become: yes }
  vars_files:
    - group_vars/geerlingguy.yml


- hosts: database
  user: "{{ ansible_user }}"

  roles:
    - { role: geerlingguy.mysql, when: install_mariadb | bool, become: yes }
    - { role: mariadb-config }
  handlers:
    - include: handlers/restarts.yml
  vars_files:
    - group_vars/geerlingguy.yml


- hosts: activemq
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-packages-repo-setup }
    - { role: opencast-shims }
    - { role: activemq-packages-install }
    - { role: activemq-config }
  handlers:
    - include: handlers/restarts.yml

- hosts: elasticsearch
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-packages-repo-setup }
    - { role: elasticsearch-packages-install }


- hosts: opencast
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-create-user }
    - { role: opencast-shims }
    - { role: nfs-client, when: handle_network_mounts | bool }
    - { role: opencast-packages-repo-setup }
    - { role: packaged-opencast-runtime-deps }
    - { role: nginxinc.nginx, when: install_nginx | bool, become: yes }
    - { role: nginxinc.nginx_config, when: install_nginx | bool, become: yes }
    - { role: opencast-packages-install }
    - { role: opencast-config }
    - { role: aws-ami, tags: "ami", when: build_ami | bool }
  handlers:
    - include: handlers/restarts.yml
  vars_files:
    - group_vars/nginx.yml
    - group_vars/geerlingguy.yml

