---

# For Let's Encrypt certs #TODO
#- src: geerlingguy.git
#- src: geerlingguy.certbot

# For reverse proxying
- src: nginxinc.nginx
  version: 0.19.2
- src: nginxinc.nginx_config
  version: 0.3.3

# NFS #TODO
- src: geerlingguy.nfs
  version: 2.0.0

# Elasticsearch
- src: elastic.elasticsearch
  version: v7.9.3

# Database
- src: geerlingguy.mysql
  version: 3.3.1

