---

# For Let's Encrypt certs #TODO
#- src: geerlingguy.git
#- src: geerlingguy.certbot

# For reverse proxying
- src: nginxinc.nginx
  version: 0.23.1
- src: nginxinc.nginx_config
  version: 0.5.1

# NFS #TODO
- src: geerlingguy.nfs
  version: 2.0.0

# Elasticsearch
- src: elastic.elasticsearch
  version: v7.10.2

# Database
- src: geerlingguy.mysql
  version: 4.1.0

