---

# For Let's Encrypt certs #TODO
#- src: geerlingguy.git
#- src: geerlingguy.certbot

# For reverse proxying
- src: nginxinc.nginx

# NFS #TODO
- src: geerlingguy.nfs
  version: 2.0.0

# Database
- src: geerlingguy.mysql
  version: 3.3.1

