---

# For Let's Encrypt certs #TODO
#- src: geerlingguy.git
#- src: geerlingguy.certbot

# For reverse proxying
- src: nginxinc.nginx

# NFS #TODO
- src: geerlingguy.nfs

# Database
- src: geerlingguy.mysql

# Elasticsearch
- src: elastic.elasticsearch
