---
# This playbook resets the database and filesystem back to default, but leaves the configuration alone.

- hosts: database
  user: "{{ ansible_user }}"

  roles:
    - { role: mariadb-clean }
    - { role: mariadb-config }


- hosts: opencast
  user: "{{ ansible_user }}"

  roles:
    - { role: opencast-clean }
