---

- name: Populate service facts
  service_facts:

- name: Stopping Opencast
  service:
    name: opencast
    state: stopped
  ignore_errors: "{{ true if uninstall is defined else false }}"
  when: hostvars[inventory_hostname]['services']['opencast'] is defined
  become: yes

# We do this with shell rather than the file module because oc_storage_dir is
# an NFS mount, and thus can't be reliably deleted and recreated
- name: Cleaning Opencast NFS filesystem
  shell: "rm -rf {{ item }}/*"
  become_user: "{{ oc_user }}"
  become: yes
  with_items:
    - "{{ oc_storage_dir }}"
  when: inventory_hostname == admin_node
  notify: "restart opencast"

# We do this with shell rather than the file module because oc_storage_dir is
# an NFS mount, and thus can't be reliably deleted and recreated
- name: Cleaning Opencast local filesystem
  shell: "rm -rf {{ item }}/*"
  become: yes
  with_items:
    - "{{ oc_log_dir }}"
    - "{{ oc_local_dir }}"
  notify: "restart opencast"
