---

- name: Populate service facts
  service_facts:

- name: Stopping Opencast
  service:
    name: opencast
    state: stopped
  ignore_errors: "{{ true if uninstall is defined else false }}"
  when: hostvars[inventory_hostname]['services']['opencast'] is defined
  become: yes

- name: Umount NFS mount if mounted
  mount:
    name: "{{ oc_storage_dir }}"
    state: unmounted
  when: handle_network_mounts | bool and 'fileserver' not in group_names
  become: yes

# We do this with shell rather than the file module because oc_storage_dir is
# an NFS mount, and thus can't be reliably deleted and recreated
- name: Cleaning Opencast filesystem
  shell: "rm -rf {{ item }}/*"
  become: yes
  with_items:
    - "{{ oc_log_dir }}"
    - "{{ oc_local_dir }}"
    - "{{ oc_storage_dir }}"
  notify: "restart opencast"

- name: Remounting NFS mount if it was mounted
  mount:
    name: "{{ oc_storage_dir }}"
    src: "{{ nfs_server }}:{{ oc_storage_dir }}"
    fstype: nfs
    state: mounted
    opts: "rw,sync,vers=3"
  when: handle_network_mounts | bool and 'fileserver' not in group_names
  become: yes
