---

- name: Removing existing Opencast repository
  file:
    path: /etc/apt/sources.list.d/{{ item }}
    state: absent
  loop:
    - opencast-stable.list
    - opencast.list
  become: yes

- name: Installing apt-transport-https and gpg
  apt:
    pkg: ['gpg', 'apt-transport-https', 'ca-certificates']
    state: latest
    update_cache: yes
  become: yes
  register: https
  until: https is not failed
  retries: 5
  delay: 3

- name: Downloading default repo signing key
  get_url:
    url: "{{ default_oc_deb_key_url }}"
    dest: /etc/apt/trusted.gpg.d/opencast-stable.asc
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Downloading {{ deb_repo_suite }} signing key
  get_url:
    url: "{{ oc_deb_key_url }}"
    dest: /etc/apt/trusted.gpg.d/opencast-other.asc
    owner: root
    group: root
    mode: 0644
  when: default_oc_deb_key_url != oc_deb_key_url
  become: yes

- name: Adding {{ default_repo_host }} stable to repo list
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/opencast-stable.asc] {{ default_oc_deb_repo_url }} {{ oc_package_version }}.x stable"
    filename: opencast-stable
    state: present
    update_cache: yes
  become: yes

- name: Adding optional {{ oc_deb_repo_url }} {{ deb_repo_suite }} to repo list
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/opencast-{{ (default_oc_deb_key_url == oc_deb_key_url) | ternary('stable', 'other') }}.asc] {{ oc_deb_repo_url }} {{ oc_package_version }}.x {{ deb_repo_suite }}"
    filename: opencast
    state: present
    update_cache: yes
  when: default_oc_deb_repo_url != oc_deb_repo_url or default_deb_repo_suite != deb_repo_suite
  become: yes

