---

- name: Removing existing Opencast repository
  file:
    path: /etc/apt/sources.list.d/pkg_opencast_org_debian.list
    state: absent
  become: yes

- name: Installing apt-transport-https
  apt:
    pkg: ['apt-transport-https', 'ca-certificates']
    state: latest
    update_cache: yes
  become: yes

- name: Adding Debian signing key to apt keyring
  apt_key:
    url: "{{ default_oc_deb_key_url }}"
    id: "{{ default_oc_deb_key_id }}"
    state: present
  become: yes

- name: Adding {{ default_repo_host }} stable to repo list
  apt_repository:
    repo: "deb {{ default_oc_deb_repo_url }} stable/"
    state: present
  become: yes

- name: Adding Debian signing key associated with optional repo to apt keyring
  apt_key:
    url: "{{ oc_deb_key_url }}"
    id: "{{ oc_deb_key_id }}"
    state: present
  when: oc_deb_key_url != default_oc_deb_key_url
  become: yes

- name: Adding optional {{ deb_repo_suite }} to repo list
  apt_repository:
    repo: "deb {{ oc_deb_repo_url }} {{ deb_repo_suite }}/"
    state: present
    update_cache: yes
  when: deb_repo_suite != default_deb_repo_suite
  become: yes

