---

- name: Removing existing Opencast repository
  file:
    path: /etc/apt/sources.list.d/opencast.list
    state: absent
  become: yes

- name: Installing apt-transport-https and gpg
  apt:
    pkg: ['gpg', 'apt-transport-https', 'ca-certificates']
    state: latest
    update_cache: yes
  become: yes
  register: https
  until: https is not failed
  retries: 5
  delay: 3

- name: Downloading default repo signing key
  get_url:
    url: "{{ default_oc_deb_key_url }}"
    dest: /tmp/opencast-stable.gpg
  become: yes

- name: Packaging key for apt
  shell: gpg --no-tty --no-default-keyring --keyring=./temp.gpg --import /tmp/opencast-stable.gpg && gpg --no-tty --no-default-keyring --keyring=./temp.gpg --export --output ./opencast-stable.gpg && mv opencast-stable.gpg /etc/apt/trusted.gpg.d/opencast-stable.gpg
  become: yes

- name: Cleaning up temp keyring files
  file:
    path: "{{ item }}"
    state: absent
  become: yes
  loop:
    - temp.gpg
    - temp.gpg~
    - /tmp/opencast-stable.gpg

- name: Downloading {{ deb_repo_suite }} signing key
  get_url:
    url: "{{ oc_deb_key_url }}"
    dest: "/tmp/opencast-{{ deb_repo_suite }}.gpg"
  become: yes

- name: Packaging key for apt
  shell: gpg --no-tty --no-default-keyring --keyring=./temp.gpg --import /tmp/opencast-{{ deb_repo_suite }}.gpg && gpg --no-tty --no-default-keyring --keyring=./temp.gpg --export --output ./opencast-{{ deb_repo_suite }}.gpg && mv opencast-{{ deb_repo_suite }}.gpg /etc/apt/trusted.gpg.d/opencast-{{ deb_repo_suite }}.gpg
  become: yes

- name: Cleaning up temp keyring files
  file:
    path: "{{ item }}"
    state: absent
  become: yes
  loop:
    - temp.gpg
    - temp.gpg~
    - /tmp/opencast-{{ deb_repo_suite }}.gpg

- name: Adding {{ default_repo_host }} stable to repo list
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/opencast-stable.gpg] {{ default_oc_deb_repo_url }} {{ oc_package_version}}.x stable"
    filename: opencast
    state: present
  become: yes

- name: Adding optional {{ deb_repo_suite }} to repo list
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/opencast-{{ deb_repo_suite }}.gpg] {{ oc_deb_repo_url }} {{ oc_package_version }}.x {{ deb_repo_suite }}"
    filename: opencast
    state: present
    update_cache: yes
  when: deb_repo_suite != default_deb_repo_suite
  become: yes

