---

- name: Determining installed Opencast repositories
  shell:
    cmd: "cat /etc/yum.repos.d/*.repo | grep opencast | grep -v opencast-{{ rpm_repo_suite }}-noarch | grep -v x86_64 | grep -o 'opencast-[a-z]*-[a-z0-9_]*'"
  register: excludes

- name: Installing Opencast
  yum:
    name: "{{ lookup('vars', opencast_node_type) }}"
    state: present
    update_cache: yes
    disablerepo: "{{ excludes.stdout_lines | join(',') }}"
    enablerepo: 'opencast-{{ rpm_repo_suite }}-noarch'
  become: yes
  register: install
  until: install is not failed
  retries: 5
  delay: 3
