---

- name: Installing Opencast
  apt:
    name: "{{ lookup('vars', opencast_node_type) }}"
    state: latest
    update_cache: yes
  become: yes
  register: install
  until: install is not failed
  retries: 5
  delay: 3
