---

#The user to run the Opencast service as.
oc_user: opencast

#The group to run the Opencast service as.
oc_group: opencast

#The admin node, taken from the three admin class groups.  Note the order of precedence.
admin_node: "{{ groups['admin_node'][0] }}"

#The presentations nodes, taken from the three presentations class groups.  Note the order of precedence.
presentation_node: "{{ groups['presentation_node'][0] }}"

#The opensearch node, taken from the opensearch group.
opensearch_node: "{{ groups['opensearch'][0] }}"


### Network settings ###

#The protocol for Opencast to use.  Defaults to http, should be changed to https for production use.
oc_protocol: https

#Whether to connect to Elastic/Opensearch via HTTPS
# The logic here is that if we're handling SSL, then yes we should.  If not, then probably not, but this can be easily overridden
elasticsearch_https: handle_https | default(false)

#The default Opensearch opencast user
elasticsearch_oc_user: admin

#The default Opensearch opencast pass
elasticsearch_oc_pass: admin

### Database settings ###

#The database server, including port if not using default ports
oc_db_host: "{{ (inventory_hostname == groups['database'][0]) | ternary('localhost', groups['database'][0]) }}"


### Directory settings ###

#Where to store opencast's configuration data.
oc_config_dir: "/etc/opencast"

#Where to store Opencast's logs.
oc_log_dir: "/var/log/opencast"

#The local storage directory for Openast.  This will contain things like Solr indexes.
oc_local_dir: "/var/lib/opencast"

#The local directory to use for a workspace.  This should be fast, but transient storage.
oc_workspace_root: "{{ oc_local_dir }}/workspace"


### Mail settings ###

# Whether to actually relay e-mails that are handed to the
# smtp service (production mode) or silently drop them
# (test mode).
# Accepted values are 'production' or 'test'
oc_mail_mode: test

# The transport protocol to use
# Accepted values are 'smtp' or 'smtps'
oc_mail_transport: smtp

# Hostname or IP address of the SMTP server.
oc_mail_smtp_host: localhost
oc_mail_smtps_host: localhost

# Which port to use when talking to the SMTP server.
# The default ports are 25 for plain SMTP, 465 for
# SMTPs and 587 for authenticated SMTP + TLS
oc_mail_smtp_port: 25
oc_mail_smtps_port: 465

# Whether to enable TLS over SMTP. Possible values are
# 'true or false'.
oc_mail_smtp_starttls: false
oc_mail_smtps_starttls: false

# Username to be used when authenticating with the SMTP
# server in conjunction with mail.password.
# Leave empty if no authentication is required.
oc_mail_username:

# Password to be used when authenticating with the SMPT
# server in conjunction with mail.user.
# Leave empty if no authentication is required.
oc_mail_password:

# The sender mail address. Some SMTP services require
# this to be a valid e-mail address from their mail domain.
oc_mail_from:
