---

### Network settings ###

#The protocol for Opencast to use.  Defaults to http, should be changed to https for production use.
oc_protocol: http

### Database settings ###

#The database server, including port if not using default ports
oc_db_host: "{{ (inventory_hostname == groups['database'][0]) | ternary('localhost', groups['database'][0]) }}"

#True to generate the DB tables on startup, false assumes schema is already present
oc_db_ddl: false


### Directory settings ###

#The local directory to use for a workspace.  This should be fast, but transient storage.
oc_workspace_root: "{{ oc_local_dir }}/workspace"


### Mail settings ###

# Whether to actually relay e-mails that are handed to the
# smtp service (production mode) or silently drop them
# (test mode).
# Accepted values are 'production' or 'test'
oc_mail_mode: test

# The transport protocol to use
# Accepted values are 'smtp' or 'smtps'
oc_mail_transport: smtp

# Hostname or IP address of the SMTP server.
oc_mail_smtp_host: localhost
oc_mail_smtps_host: localhost

# Which port to use when talking to the SMTP server.
# The default ports are 25 for plain SMTP, 465 for
# SMTPs and 587 for authenticated SMTP + TLS
oc_mail_smtp_port: 25
oc_mail_smtps_port: 465

# Whether to enable TLS over SMTP. Possible values are
# 'true or false'.
oc_mail_smtp_starttls: false
oc_mail_smtps_starttls: false

# Username to be used when authenticating with the SMTP
# server in conjunction with mail.password.
# Leave empty if no authentication is required.
oc_mail_username:

# Password to be used when authenticating with the SMPT
# server in conjunction with mail.user.
# Leave empty if no authentication is required.
oc_mail_password:

# The sender mail address. Some SMTP services require
# this to be a valid e-mail address from their mail domain.
oc_mail_from:
