---

- include: ../../pyca-stop/tasks/main.yml

- name: Stop and disable pyCA
  service: name=pyca state=stopped enabled=no
  sudo: yes
  when: pycapresent.stat.exists is defined and pycapresent.stat.exists == True

- name: Removing pyCA init script
  file: path=/etc/init.d/pyca state=absent
  sudo: yes
  when: pycapresent.stat.exists is defined and pycapresent.stat.exists == True

- name: Removing pyCA log directory
  file: path={{pyca_log_dir}} state=absent
  sudo: yes
  when: pycapresent.stat.exists is defined and pycapresent.stat.exists == True

- name: Wipe Matterhorn root directory
  file: path={{mh_parent_dir}} state=absent
  sudo: yes
