- name: Installing Firewalld
  yum:
    name: firewalld
    state: present
  become: yes
  register: firewall
  until: firewall is not failed
  retries: 5
  delay: 3

- name: Make sure firewall is running
  systemd:
    name: firewalld
    state: started
    enabled: yes
  become: yes

- name: Allowing MariaDB, nginx, NFS, and related services past the firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    zone: public
    immediate: true
  with_items:
    - mountd
    - rpc-bind
    - nfs
    - http
    - mysql
  become: yes

- name: Installing semanagement modules
  package:
    name: libsemanage-python
    state: present
  when: ansible_selinux["status"] == "enabled"
  become: yes
  register: semanage
  until: semanage is not failed
  retries: 5
  delay: 3

- name: Allowing nginx to be a reverse proxy
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux["status"] == "enabled"
  become: yes

