---

- name: Adding Debian stretch-backports to repo list for Openjdk 11
  apt_repository:
    repo: "deb http://deb.debian.org/debian stretch-backports main contrib non-free"
    state: present
    update_cache: yes
  become: yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version < "10"

- name: Pinning Debian version so we don't update the whole system
  template:
    src: "99defaultrelease"
    dest: "/etc/apt/apt.conf.d/"
    owner: root
    group: root
    mode: 0644
  become: yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version < "10"

- name: Installing Java 11 from Debian stretch-backports
  apt:
    name: openjdk-11-jdk
    default_release: stretch-backports
    state: present
  become: yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version < "10"
