---

- name: Loading platform variables
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: Installing NFS client
  package:
    pkg: "{{ nfs_client_packages }}"
    state: present
  become: yes
  when: nfs_server is defined and 'fileserver' not in group_names

- name: Setting up NFS mounts
  mount:
    name: "{{ oc_storage_dir }}"
    src: "{{ nfs_server }}:{{ oc_storage_dir }}"
    fstype: nfs
    state: mounted
    opts: "rw,sync,vers=3"
  become: yes
  when: nfs_server is defined and 'fileserver' not in group_names
