---

- name: "Install script to configure Opencast for the instance"
  copy:
    src: "opencast_allinone_config.sh"
    dest: "/var/lib/cloud/scripts/per-instance"
    mode: 0755
  become: yes
  when: "'allinone' in group_names"
  tags: allinone

- name: Make Opencast wait for cloud-init to complete
  copy:
    src: override.conf
    dest: /etc/systemd/system/opencast.service.d/
  become: yes
