---

  # Try creating DB ourselves so can register change
- name: Create the Opencast database
  mysql_db:
    name: "{{ oc_db_schema }}"
    state: present
  notify: "Copying schema to database server"
  become: yes

