---

- name: Ensuring pip is present on the system
  package:
    name: python3-pip
    state: present
  become: yes

#Required to create the DB
- name: Installing PyMySQL
  pip:
    name: PyMySQL
    state: present
  become: yes

- name: Create the Opencast database
  mysql_db:
    name: "{{ oc_db_schema }}"
    login_user: "{{ oc_db_user }}"
    login_password: "{{ oc_db_pass }}"
    state: present
  become: yes

